# Site settings
title: Vincent-Duan
email: "duanding.yang@163.com"
description: "This is Vincent Duan"
#baseurl: "/MyBlog"
permalink: /:year/:title
production_url : http://vincentduan.github.io

# Social account
#twitter:  PeiwenLu
weibo:    vincentDingDing
github:   vincentduan
#codepen:  P233
# dribbble: username


# Comment
# disqus_shortname:


# Google Analytics
#google_analytics: UA-60830414-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
